### PR TITLE
Add a workaround for a recent nvidia driver bug

### LINKED ISSUE #5205: 1.9.0-jumbo-1+bleeding-84a4aeb20 - wpapsk-opencl broken after driver/cuda update
OpenCL broken (after driver/cuda update) on some hash modes:

word.list content:
hashcat!

pmkid.john content:
`2582a8281bf9d4308d6f5731d0e61c61*4604ba734d4e*89acf0e761f4*ed487162465a774bfba60eb603a39f3a`

both taken from https://hashcat.net/wiki/doku.php?id=example_hashes
```
$ john -w:word.list --format=wpapsk-opencl pmkid.john
Device 1@tux1: NVIDIA GeForce GTX 1080 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk-opencl, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 OpenCL])
5 errors generated.
Options used: -I opencl -cl-mad-enable -DSM_MAJOR=6 -DSM_MINOR=1 -D__GPU__ -DDEVICE_INFO=524306 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=520 -DDEV_VER_MINOR=56 -D_OPENCL_COMPILER -DHASH_LOOPS=105 -DITERATIONS=4095 -DPLAINTEXT_LENGTH=63 -DV_WIDTH=1 /usr/share/john/opencl/wpapsk_kernel.cl
Build log: In file included from <kernel>:12:
opencl/opencl_sha2_ctx.h:122:24: error: passing '__generic uchar *' (aka '__generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer
                _sha256_process(ctx, ctx->buffer);
                                     ^~~~~~~~~~~
opencl/opencl_sha2_ctx.h:40:51: note: passing argument to parameter 'data' here
void _sha256_process(SHA256_CTX *ctx, const uchar data[64]) {
                                                  ^
opencl/opencl_sha2_ctx.h:130:24: error: passing 'const __generic uchar *' (aka 'const __generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer
                _sha256_process(ctx, input);
                                     ^~~~~
opencl/opencl_sha2_ctx.h:40:51: note: passing argument to parameter 'data' here
void _sha256_process(SHA256_CTX *ctx, const uchar data[64]) {
                                                  ^
opencl/opencl_sha2_ctx.h:291:24: error: passing '__generic uchar *' (aka '__generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer
                _sha512_process(ctx, ctx->buffer);
                                     ^~~~~~~~~~~
opencl/opencl_sha2_ctx.h:209:51: note: passing argument to parameter 'data' here
void _sha512_process(SHA512_CTX *ctx, const uchar data[128]) {
                                                  ^
opencl/opencl_sha2_ctx.h:299:24: error: passing 'const __generic uchar *' (aka 'const __generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer
                _sha512_process(ctx, input);
                                     ^~~~~
opencl/opencl_sha2_ctx.h:209:51: note: passing argument to parameter 'data' here
void _sha512_process(SHA512_CTX *ctx, const uchar data[128]) {
                                                  ^
<kernel>:549:15: error: passing '__generic uchar *' (aka '__generic unsigned char *') to parameter of type 'uchar *' (aka 'unsigned char *') changes address space of pointer
        SHA256_Final(mac, &ctx);
                     ^~~
opencl/opencl_sha2_ctx.h:145:25: note: passing argument to parameter 'output' here
void SHA256_Final(uchar output[32], SHA256_CTX *ctx) {
                        ^

Error building kernel /usr/share/john/opencl/wpapsk_kernel.cl. DEVICE_INFO=524306
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1296 - clBuildProgram

```

Additional information about john:
$ john --list=build-info
Version: 1.9.0-jumbo-1+bleeding-84a4aeb20 2022-10-17 14:03:56 +0200
Build: linux-gnu 64-bit x86_64 AVX AC MPI + OMP OPENCL
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
System-wide exec: /usr/bin
System-wide home: /usr/share/john
Private home: ~/.john
CPU tests: AVX
CPU fallback binary: john-non-avx
$JOHN is /usr/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 12.2.0
GNU libc version: 2.36 (loaded: 2.36)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 01010111f
OpenSSL 1.1.1q  5 Jul 2022
GMP library version: 6.2.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 29 ns
Total physical host memory: 15944 MiB
Available physical host memory: 12610 MiB
Terminal locale string: de_DE.utf8
Parsed terminal locale: UTF-8

Additional information about distribution and driver :
$ uname -a
Linux tux1 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux

$ pacman -Q | grep nvidia
nvidia 520.56.06-4
nvidia-settings 520.56.06-1
nvidia-utils 520.56.06-2
opencl-nvidia 520.56.06-2

$ pacman -Q | grep cuda
cuda 11.8.0-1

Similar to this (fixed)
https://github.com/openwall/john/issues/4667

Looks like NVIDA changed some API calls from time to time.

### PR DESCRIPTION
**Pull request by magnumripper**
Array arguments in kernel functions would trigger bugs unless explicitly reverting to OpenCL 1.2.

Closes #5205

### CODE REVIEW

**Comment by magnumripper** [comment]
Needs testing with older and newer drivers before merging

**Comment by magnumripper** [comment]
Here's an idea: We currently have a john.conf setting `GlobalBuildOpts` where one can put OpenCL build options like this. We could add two more of them, eg. `NvidiaBuildOpts` and `AMDbuildOpts` and put `-cl-std=CL1.2` in the former of them instead of hardcoding it.

File: src/opencl_common.c [hunk 1]
```diff
@@ -1163,7 +1163,7 @@ static char *get_build_opts(int sequential_id, const char *opts)
 #else
 	        (options.verbosity >= VERB_MAX &&
 	         gpu_nvidia(device_info[sequential_id])) ?
-	         "-cl-nv-verbose " : "",
+	         "-cl-nv-verbose -cl-std=CL1.2 " : "",
```
Comment (magnumripper) [inline src/opencl_common.c]: This doesn't work - except when verbosity is bumped (obvious if you look closer).

**Comment by magnumripper** [comment]
Completely rewritten now: We simply add `-cl-std=CL1.2` in case device is OpenCL 2.0 or higher. Tested on all gear I could find, and really should work fine on any platform.
