### PR TITLE
fixes for crashes found with fuzzing

### LINKED ISSUE #5157: crashes under ASan from fuzzing: PBKDF2-HMAC-MD5, SSH, hdaa, scrypt, and others
`ssh`:
```
$ perl -le 'print q{$sshng$1$16$570F498F6FF732775EE38648130F600D$10000$} . "00" x 10000' > t.pw
$ ./john/run/john t.pw
[...]
==395326==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x625000002188 at pc 0x562401e4a8c2 bp 0x7ffd00791a40 sp 0x7ffd00791a38
READ of size 1 at 0x625000002188 thread T0
    #0 0x562401e4a8c1 in ssh_get_salt /home/user/john/src/ssh_common_plug.c:121
    #1 0x562401ee374b in ldr_load_pw_line /home/user/john/src/loader.c:1050
    #2 0x562401ede227 in read_file /home/user/john/src/loader.c:260
    #3 0x562401ee61eb in ldr_load_pw_file /home/user/john/src/loader.c:1203
    #4 0x562401ed5583 in john_load /home/user/john/src/john.c:1134
    #5 0x562401ed5583 in john_init /home/user/john/src/john.c:1578
    #6 0x562401ed5583 in main /home/user/john/src/john.c:2065
    #7 0x7f98f0943d09 in __libc_start_main ../csu/libc-start.c:308
    #8 0x5624019d6489 in _start (/home/user/john/run/john+0x2dd489)

0x625000002188 is located 0 bytes to the right of 8328-byte region [0x625000000100,0x625000002188)
allocated by thread T0 here:
    #0 0x7f98f105e817 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:452
    #1 0x562401efd7c5 in xstrdup /home/user/john/src/memory.c:136
    #2 0x562401e4a6a2 in ssh_get_salt /home/user/john/src/ssh_common_plug.c:99
    #3 0x562401ee374b in ldr_load_pw_line /home/user/john/src/loader.c:1050
```

`hdaa`:
```
$ perl -le 'print q{$response$8663faf2337dbcb2c52882807592ec2c$} . "9" x 200 . q{user$myrealm$GET$/$8c12bd8f728afe56d45a0ce846b70e5a$}' > t.pw
$ ./john/run/john t.pw
AddressSanitizer:DEADLYSIGNAL
=================================================================
==395331==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fc529aa8b71 bp 0x7ffcfc70b580 sp 0x7ffcfc70ad28 T0)
==395331==The signal is caused by a READ memory access.
==395331==Hint: address points to the zero page.
    #0 0x7fc529aa8b71  (/lib/x86_64-linux-gnu/libc.so.6+0x15fb71)
    #1 0x7fc52a06fa8c in __interceptor_strlen ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:368
    #2 0x5629dd5550fb in get_salt /home/user/john/src/HDAA_fmt_plug.c:653
    #3 0x5629dd7dd74b in ldr_load_pw_line /home/user/john/src/loader.c:1050
```

`pbkdf2-hmac-md5`:
```
$ perl -le 'print q{$pbkdf2-hmac-md5$1000$} . "3" x 230 . q{$aaaaaaaaaaaaaaaaaaaaaaaaaa$} . "9" x 200 . q{$}' > t.pw
$ ./john/run/john t.pw
[...]
==395408==ERROR: AddressSanitizer: global-buffer-overflow on address 0x555d07fd1100 at pc 0x555d0618a3e3 bp 0x7ffec2b35260 sp 0x7ffec2b35258
READ of size 1 at 0x555d07fd1100 thread T0
    #0 0x555d0618a3e2 in pbkdf2_hmac_md5_binary /home/user/john/src/pbkdf2_hmac_common_plug.c:285
    #1 0x555d0629b45a in ldr_load_pw_line /home/user/john/src/loader.c:990
    #2 0x555d06295227 in read_file /home/user/john/src/loader.c:260
    #3 0x555d0629d1eb in ldr_load_pw_file /home/user/john/src/loader.c:1203
    #4 0x555d0628c583 in john_load /home/user/john/src/john.c:1134
    #5 0x555d0628c583 in john_init /home/user/john/src/john.c:1578
    #6 0x555d0628c583 in main /home/user/john/src/john.c:2065
    #7 0x7f4334879d09 in __libc_start_main ../csu/libc-start.c:308
    #8 0x555d05d8d489 in _start (/home/user/john/run/john+0x2dd489)

0x555d07fd1100 is located 32 bytes to the left of global variable 'buf' defined in 'pbkdf2_hmac_common_plug.c:133:4' (0x555d07fd1120) of size 16
0x555d07fd1100 is located 0 bytes to the right of global variable 'out' defined in 'pbkdf2_hmac_common_plug.c:260:14' (0x555d07fd0f00) of size 512
```

`scrypt`:
```
$ perl -le 'print q{$7$C6..../....SodiumChloride$} . "9" x 200 . q{kBGj9fHznVYFQMEn/qDCfrDevf9YDtcDdKvEqHJLV8D}' > t.pw
$ ./john/run/john t.pw
[...]
==395412==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55b3d36a3820 at pc 0x7f12946ce2c9 bp 0x7ffd3b07d5a0 sp 0x7ffd3b07cd50
READ of size 257 at 0x55b3d36a3820 thread T0
    #0 0x7f12946ce2c8 in __interceptor_strrchr ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:719
    #1 0x55b3d279c1dd in binary_hash_4 /home/user/john/src/scrypt_fmt.c:355
    #2 0x55b3d2c4d47c in ldr_load_pw_line /home/user/john/src/loader.c:991
    #3 0x55b3d2c47227 in read_file /home/user/john/src/loader.c:260
    #4 0x55b3d2c4f1eb in ldr_load_pw_file /home/user/john/src/loader.c:1203
    #5 0x55b3d2c3e583 in john_load /home/user/john/src/john.c:1134
    #6 0x55b3d2c3e583 in john_init /home/user/john/src/john.c:1578
    #7 0x55b3d2c3e583 in main /home/user/john/src/john.c:2065
    #8 0x7f1293fcdd09 in __libc_start_main ../csu/libc-start.c:308
    #9 0x55b3d273f489 in _start (/home/user/john/run/john+0x2dd489)

0x55b3d36a3820 is located 32 bytes to the left of global variable 'out' defined in 'scrypt_fmt.c:286:14' (0x55b3d36a3840) of size 256
0x55b3d36a3820 is located 0 bytes to the right of global variable 'out' defined in 'scrypt_fmt.c:279:14' (0x55b3d36a3720) of size 256
```

### PR DESCRIPTION
**Pull request by AlekseyCherepanov**
It closes #5157. It affects the following formats:
```
rsvp,gpg,bitlocker,net-md5,o10glogon,o3logon,SSHA512,ike,dynamic_15,vtp,nsec3,wowsrp,SSH,hdaa,PBKDF2-HMAC-MD5,krb5asrep,scrypt,dynamic_1552,bitlocker-opencl,gpg-opencl,SSH-opencl,PBKDF2-HMAC-MD5-opencl
```

`--test=0` and `--fuzz=../run/fuzz.dic` are ok.

I prepared fixes quickly, so some of them might be suboptimal.

JFYI I was caught by the following problem fixing `wowsrp`: I increased buffer size right in `get_salt` instead of change to `SALT_SIZE`. So salt would be truncated and there would be a crash during cracking or uncrackable hash. Self-tests do not catch such mistake: all tests worked well with smaller buffer. Fuzzer does not catch it too.

My fixes for memory leaks in #5158 introduced use-after-free for dynamic salts because `ldr_free_db` is called in fuzzer and in john.
```
==4006==ERROR: AddressSanitizer: heap-use-after-free on address 0x60d00001bbe8 at pc 0x5604db9ddef1 bp 0x7ffc3e4223f0 sp 0x7ffc3e4223e8
READ of size 1 at 0x60d00001bbe8 thread T0
    #0 0x5604db9ddef0 in dyna_salt_remove_fp /home/user/john/src/dyna_salt.c:56
    #1 0x5604dba2dd33 in ldr_free_db /home/user/john/src/loader.c:1358
    #2 0x5604dba1ede3 in john_done /home/user/john/src/john.c:1953
    #3 0x5604dba1ede3 in main /home/user/john/src/john.c:2083
```

The problem affects a subset of formats using `dyna_salt` (approximately `gpg,7z,pkzip,zip` + their opencl variants).

The last commit fixes the use-after-free. To allow excessive calls to `ldr_free_db`, I just set `db->salts` to `NULL` in `ldr_free_db`. I am not sure if it is ok. But ASan does not report leaks. I would like this bit to be reviewed better.

If everything is fine, this PR is ready. Thanks!

### CODE REVIEW

File: src/HDAA_fmt_plug.c [hunk 1]
```diff
@@ -68,6 +68,9 @@ john_register_one(&fmt_HDAA);
 // This is 8 x 64 bytes, so in MMX/SSE2 we support up to 9 limbs of MD5
 #define HTMP                    512
 
+// That's arbitrary because uri part is not limited by anything natural.
+#define MAX_CIPHERTEXT_LEN      8096
```
Comment (solardiz) [inline src/HDAA_fmt_plug.c]: 8096 is a weird choice for an arbitrary limit - perhaps you meant 4096 or 8192?

File: src/HDAA_fmt_plug.c [hunk 2]
```diff
@@ -224,8 +245,10 @@ static char *split(char *ciphertext, int index, struct fmt_main *self)
 	cp = strchr(cp+1, '$'); if (!cp) return ciphertext;
 	// now if we have $binary_hash$ then we remove the last '$' char
 	if (strlen(cp) == 1 + BINARY_SIZE*2 + 1) {
-		static char out[256];
-		strnzcpy(out, ciphertext, sizeof(out));
+		static char *out;
+		if (!out)
+			out = mem_alloc_tiny(MAX_CIPHERTEXT_LEN, MEM_ALIGN_NONE);
+		strnzcpy(out, ciphertext, MAX_CIPHERTEXT_LEN);
 		out[strlen(out)-1] = 0;
```
Comment (solardiz) [inline src/HDAA_fmt_plug.c:252]: I think you need to allocate `MAX_CIPHERTEXT_LEN + 1` and pass that to `strnzcpy`, so that `MAX_CIPHERTEXT_LEN` is treated literally as the maximum length, which is also how you treat ti in the check in `valid`.

Also, drop the unneeded `out[strlen(out)-1] = 0;`

**Review by solardiz — APPROVED** [review]
I only looked at what's in patch context. I made some nitpicks, but overall this looks fine. Thank you, Aleksey!

**Comment by solardiz** [comment]
> JFYI I was caught by the following problem fixing wowsrp: I increased buffer size right in get_salt instead of change to SALT_SIZE. So salt would be truncated and there would be a crash during cracking or uncrackable hash. Self-tests do not catch such mistake: all tests worked well with smaller buffer. Fuzzer does not catch it too.

I guess this means we need to enhance the self-tests to truncate a copy of the returned salt to the format's `salt_size`.

However, we seem to have no way to _guarantee_ the data following the truncated salt won't just happen to match what's in the full returned salt (unless we over-read the returned salt just to ensure we produce different e.g. first byte there, but such over-reading is unsafe, so let's not do it). So this will be a best-effort test, which is fine. We can over-allocate, say, 1 byte to put some varying value in that extra byte.

File: src/HDAA_fmt_plug.c (hunk 2 above)
Comment (AlekseyCherepanov) [reply src/HDAA_fmt_plug.c:252]: `out[strlen(out)-1] = 0;` is needed: it removes the last char (`$`).

But I need `+1` for the length. Otherwise with input of max length, `strnzcpy` would remove the last char itself and then the next line would remove one more char.

File: src/HDAA_fmt_plug.c (hunk 1 above)
Comment (AlekseyCherepanov) [reply src/HDAA_fmt_plug.c]: Ouch, I meant 8192 indeed.

**Comment by AlekseyCherepanov** [comment]
I fixed `hdaa: harden valid()...` commit and rebased further commits on it. I used `magit-commit-instant-fixup` in emacs, that should be something like `git commit --fixup=... ...` + `git rebase --autosquash ...`. So all further commits are re-written. With such number of commits, button `Compare` seems invaluable.

**Comment by solardiz** [comment]
> With such number of commits, button `Compare` seems invaluable.

Yes, but it only shows cumulative changes - it would not help detect e.g. the desired changes inadvertently being in a wrong commit, or some commit introducing extra changes that another commit then removes. I wish GitHub provided a tool to easily detect those.

**Comment by AlekseyCherepanov** [comment]
> I guess this means we need to enhance the self-tests to truncate a copy of the returned salt to the format's `salt_size`.

I guess copying into test db truncates at `salt_size`. The problem should be that self-tests do not include cases for maximum acceptable length.

Fuzzer could find overflow for too small buffers. Static analysis could find that buffer size is not in sync with `salt_size` in the format structure (also formats where buffer size might vary depending on data). Actually debugging info should contain sizes and ASan tracks such info for heap allocations, so it should be possible to check at run-time during fuzzing.

Talking about checks of additional constraints during fuzzing, I would check that result from `split` passes `valid`.

**Comment by solardiz** [comment]
> self-tests do not include cases for maximum acceptable length.

I don't understand this.

> I would check that result from `split` passes `valid`.

Please feel free to implement that. Thanks!

**Comment by AlekseyCherepanov** [comment]
> it only shows cumulative changes
> I wish GitHub provided a tool to easily detect those.

Force-pushing to keep nice "source history" seems a popular variant of workflow and GitHub is [informed](https://github.com/github-community/community/discussions/3478) about it. OTOH I don't see discussions about highlighting commits with new changes to review breakdown of cumulative changes.

**Comment by AlekseyCherepanov** [comment]
>> self-tests do not include cases for maximum acceptable length.

Some formats has salt of variable length. Usually it is stored with padding and treated as fixed size by code outside of format. (There is dyna_salt feature allowing variable lengths without padding, but it is used for a small number of formats where really big salts can happen.) So some of formats with variable lengths of salts do not include test cases for maximum allowed length of salt. For instance, `wowsrp` has self-tests that use 22 bytes of salt at maximum, while old declared `salt_size` is 67 and new `salt_size` is 101.
