### PR TITLE
Fix mixed cost benchmarks

### LINKED ISSUE #5612: Axcrypt formats' cost, benchmark
The axcrypt formats benchmark mixed speeds:
```
Benchmarking: AxCrypt [PBKDF2-SHA512/SHA1 AES 32/64]... (16xOMP) DONE
Speed for cost 1 (iteration count) of 1337 and 60000
Raw:	14009 c/s real, 924 c/s virtual

Benchmarking: axcrypt-opencl [SHA1 AES OpenCL]... LWS=1 GWS=8192 (8192 blocks) DONE
Speed for cost 1 (iteration count) of 1337 and 60000
Raw:	2244 c/s real, 143 c/s virtual

Benchmarking: axcrypt2-opencl, AxCrypt 2.x [PBKDF2-SHA512 AES OpenCL]... LWS=1 GWS=128 (128 blocks) DONE
Speed for cost 1 (iteration count) of 28200 and 23652
Raw:	609 c/s real, 40.7 c/s virtual
```
Find hashcat's cost and use that with a benchmark_length of 0x507.

Also, the CPU format should have a second cost, for the version.

### PR DESCRIPTION
**Pull request by magnumripper**
Axcrypt: Add hashcat test vectors and set benchmark to it (for v1). Also adds version as a second cost.
Many other formats: Benchmark a single cost. Also add and use hashcat's test vectors when available, for comparisons.

Closes #5612

### CODE REVIEW

File: src/axcrypt_common.h [hunk 1]
```diff
@@ -7,6 +7,8 @@
 #include "formats.h"
 #include "dyna_salt.h"
 
+#define BENCHMARK_COMMENT       ""
+#define BENCHMARK_LENGTH        0x507
 #define FORMAT_TAG          "$axcrypt$*"
 #define FORMAT_TAG_LEN      (sizeof(FORMAT_TAG)-1)
```
Comment (solardiz) [inline src/axcrypt_common.h:13]: Inconsistent indentation?

File: src/opencl_pbkdf2_hmac_sha512_fmt_plug.c [hunk 2]
```diff
@@ -32,6 +32,8 @@ john_register_one(&fmt_opencl_pbkdf2_sha512);
 #define FORMAT_LABEL             "PBKDF2-HMAC-SHA512-opencl"
 #define FORMAT_NAME              "GRUB2 / OS X 10.8+"
 #define ALGORITHM_NAME           "PBKDF2-SHA512 OpenCL"
+#define BENCHMARK_COMMENT       ""
+#define BENCHMARK_LENGTH        0x107
```
Comment (solardiz) [inline src/opencl_pbkdf2_hmac_sha512_fmt_plug.c]: Inconsistent indentation?

**Review by solardiz — APPROVED** [review]
Mostly looks good to me
