### PR TITLE
Warn when using the pre-configured wordlist

### LINKED ISSUE #4639: force requirement for equal sign  after --wordlist
### Steps to reproduce ###

```
john hash.txt --wordlist=words.txt  <--- this uses words.txt as wordlist
john hash.txt --wordlist words.txt  <--- this uses the john "builtin" wordlist and sees words.txt as a hash file
```

The command line should either mandate the need for the equal sign or accept that it is not used and understand that words.txt is in fact the wordlist. 

### System configuration ###
```
 john --list=build-info                                                                                                                                                                                                              1 ⨯
Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
System-wide exec: /usr/lib/john
System-wide home: /usr/share/john
Private home: ~/.john
CPU tests: AVX2
CPU fallback binary: john-xop-omp
OMP fallback binary: john-avx2-non-omp
$JOHN is /usr/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 9.2.1
GNU libc version: 2.28 (loaded: 2.31)
Crypto library: OpenSSL
OpenSSL library version: 01010103f	(loaded: 01010109f)
OpenSSL 1.1.1c  28 May 2019	(loaded: OpenSSL 1.1.1i  8 Dec 2020)
GMP library version: 6.1.2	(loaded: 6.2.1)
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

### PR DESCRIPTION
**Pull request by ghost**
Closes #4639

I prefer "a fix" like this.
```
$ john --wordlist --mask=?w?b ...              #WARNING
Device 7: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
Loaded 19 password hashes
[...]
Proceeding with wordlist:../run/password.lst, hybrid mask:?w?b
Press 'q' or Ctrl-C to abort, almost any other key for status

$ john --wordlist ...                          #WARNING
Loaded 19 password hashes
[...]
Proceeding with wordlist:../run/password.lst
Press 'q' or Ctrl-C to abort, almost any other key for status

$ john --wordlist=tst-.dic --mask=?w?b ...     #NO WARNING
Device 7: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
Loaded 19 password hashes
LWS=1 GWS=128 (128 blocks) x255 
Press 'q' or Ctrl-C to abort, almost any other key for status
```

### CODE REVIEW

File: src/wordlist.c [hunk 1]
```diff
@@ -495,12 +495,16 @@ void do_wordlist_crack(struct db_main *db, const char *name, int rules)
...
+		/* Print what file --wordlist mode uses when it runs using the
+		   pre-configured wordlist (optional parameter not informed) */
+		default_wordlist = 1;
+		if (!(name = cfg_get_param(SECTION_OPTIONS, NULL, "Wordlist")))
+		if (!(name = cfg_get_param(SECTION_OPTIONS, NULL, "Wordfile")))
+			name = options.wordlist = WORDLIST_NAME;
+	}
 
-	if ((options.flags & FLG_BATCH_CHK || rec_restored) && john_main_process) {
+	if ((options.flags & FLG_BATCH_CHK || rec_restored || default_wordlist) && john_main_process) {
```
Comment (solardiz) [inline src/wordlist.c]: I'd add braces around `options.flags & FLG_BATCH_CHK` while we're at it.

**Review by solardiz — APPROVED** [review]
