### PR TITLE
Fix state delay

### LINKED ISSUE #4519: Replace --fix-state-delay option with cracker logic
I'd like to revisit this. The tests made in #1955 were bogus in several ways (I can elaborate on how, if it's not obvious. There are loads of foot-guns in such benchmarks). I simply can't fathom how the overhead given by the `--fix-state-delay` option would ever in any case be amortized by the alleged win.

`ftell()`, no matter how stupidly implemented, can't be anything other than dereferencing a pointer (at least with non-medieval storage media: It's not I/O for sure - how the heck would your storage know where you were at and where would it store that?!). Right? So our code for avoiding that call to `ftell` **adds** a pointer, increments of it and tests of it - all that for avoiding simply dereferencing the first pointer. I can't believe that can ever render in a real-life boost. If I'm wrong, please explain it to me.

Also, I'm sure (for many reasons apart from just gut feeling) no-one actually uses the option. That means the overhead added by it (be it tiny) is always hurting.

The least we should do is move the code away from all normal code paths (nowadays we'll almost always using memory map and/or memory buffer/indexing), and while at it we should forbid the option to be used without `-wordlist` because it's otherwise rightously ignored. I forgot doing so in my recent review of mutually exclusive options.

In case I'm all wrong and skipping `fix_state()` is actually sensible at some time, I propose we do so in `cracker`, and skip it if our last call to it was eg. no more than `timer_save_interval / 10` ago. (or something such - maybe even `/ 2`).

### PR DESCRIPTION
**Pull request by magnumripper**
Cracker: Don't call fix_state more often than once per second
    
This replaces the wordlist-specific --fix-state-delay=N option and is always active, for all modes.  We ignore the option until after next release, then drop the remains of it.

Also (in separate commit) minor tweaks to signals.c per-second stuff.

Closes #4519

### CODE REVIEW

**Comment by magnumripper** [comment]
I have yet to find a regression (and there shouldn't be any) but there's a slight boost in more situations than I would have thought (although some may be normal deviation).

File: src/signals.c [hunk 1]
```diff
@@ -324,9 +327,8 @@ static void sig_handle_timer(int signum)
 #endif
 #ifndef BENCH_BUILD
 #if OS_TIMER
-	/* Some stuff only done every few seconds */
-	if (timer_save_interval < 4 ||
-	    ((timer_save_interval - timer_save_value) & 3) == 3) {
+	/* Some stuff only done every third second */
+	if (((timer_save_interval - timer_save_value) & 3) == 1) {
```
Comment (solardiz) [inline src/signals.c]: More like every fourth.

I guess the check for `== 1` instead of `== 3` is meant to trigger at least once per interval even if the interval is very short, thus eliminating the need for checking it for `< 4`? Have you tested that this is actually triggered for those short intervals?

File: src/signals.c [hunk 2]
```diff
@@ -358,8 +360,8 @@ static void sig_handle_timer(int signum)
 #else /* no OS_TIMER */
 	time = status_get_time();
 
-	/* Some stuff only done every few seconds */
-	if ((time & 3) == 3) {
+	/* Some stuff only done every third second */
+	if ((time & 3) == 1) {
```
Comment (solardiz) [inline src/signals.c]: More like every fourth.

File: src/signals.c [hunk 3]
```diff
@@ -401,7 +403,9 @@ static void sig_handle_timer(int signum)
 		event_ticksafety = event_pending = 1;
 	}
 
-#ifndef HAVE_MPI
+#ifdef HAVE_MPI
+	if (tty_has_keyboard())
+#else
```
Comment (solardiz) [inline src/signals.c:408]: If all of this commit is about MPI stuff, then perhaps MPI should be mentioned in the commit message? Alternatively, if only some of this is about MPI, then maybe the commit should be split in two.

File: src/cracker.c [hunk 4]
```diff
@@ -1060,10 +1071,14 @@ static int crk_salt_loop(void)
...
-	else
-	crk_fix_state();
+
+	if (fix_state_present && event_fix_state) {
+		if (options.flags & FLG_MASK_STACKED)
+			mask_fix_state();
+		else if (crk_fix_state)
+			crk_fix_state();
+		event_fix_state = 0;
+	}
```
Comment (solardiz) [inline src/cracker.c:1084]: Maybe instead of deciding on which function to call each time, we should conditionally set the function pointer to `mask_fix_state()` in `crk_init()`. Also, why do we need `else if` here (rather than just `else`) - is it somehow possible that we have `fix_state_present` yet aren't going to call any function here?

File: src/cracker.c [hunk 5]
```diff
@@ -1077,6 +1092,10 @@ static int crk_salt_loop(void)
 	return ext_abort;
 }
 
+/*
+ * Process an incomplete batch; This is used by mask mode before
+ * resetting the format with a changed internal mask.
+ */
 int crk_process_buffer(void)
```
Comment (solardiz) [inline src/cracker.c:1102]: I think `crk_process_buffer()` is used by more than just mask mode, and existed before we got mask mode.

File: src/cracker.c [hunk 6]
```diff
@@ -1149,10 +1172,13 @@ static int process_key(char *key)
...
-		mask_fix_state();
-	else
-	crk_fix_state();
+	if (fix_state_present && event_fix_state) {
+		if (options.flags & FLG_MASK_STACKED)
+			mask_fix_state();
+		else if (crk_fix_state)
+			crk_fix_state();
+		event_fix_state = 0;
+	}
```
Comment (solardiz) [inline src/cracker.c:1184]: Same comments as I had on the previous occurrence of this snippet. And the code duplication is another reason to make this snippet shorter by moving some of the logic into `crk_init()`.

**Review by solardiz — APPROVED** [review]
This mostly looks good to me, but I think you should edit some comments. Also, consider moving the mask mode checks into `crk_init()`, maybe with a separate commit.

File: src/cracker.c (hunk 5 above)
Comment (magnumripper) [reply src/cracker.c:1102]: No, I added it in c1d7a2f3 for mask mode for the very case documented. I'm not sure right now how the "last batch" of a run is processed, but it must be done by other means.

File: src/signals.c (hunk 1 above)
Comment (magnumripper) [reply src/signals.c]: Good call. Without testing yet, I guess it should be `== 0` but I will review this closer.

File: src/signals.c (hunk 3 above)
Comment (magnumripper) [reply src/signals.c:408]: The rest isn't. Actually this change "should" be the test for non-MPI runs as well, provided it doesn't give any regression on some systems and it might not be important enough to even profile.

Here's `tty_has_keyboard()`:
```c
int tty_has_keyboard(void)
{
#if !defined(__DJGPP__) && !defined(__MINGW32__) && !defined (_MSC_VER)
        return (tty_fd >= 0);
#else
        return !(in_stdin_mode && isatty(fileno(stdin)));
#endif
}
```
This could be very slightly worse than just `if (john_main_process)` (because of the function call, if nothing else) but in my tests it didn't matter enough to be measurable at all (on that platform).

Given that, I'm fine with just dropping this change. However, for some reason unclear to me today, MPI builds didn't even test for `john_main_process` so maybe we should instead drop the original `#ifndef` stuff and call it a day.

File: src/cracker.c (hunk 4 above)
Comment (magnumripper) [reply src/cracker.c:1084]: Right! I somehow overlooked the former (to set the function pointer). The latter (`fix_state_present` vs `if (crk_fix_state)`) is actually an artefact. I will amend it, thanks!

Comment (magnumripper) [reply src/cracker.c:1084]: Here's the deal: `mask_fix_state()` will sometimes call `crk_fix_state()` so we can't change that. Hybrid "fix state" stuff are very competent foot guns, I have plans to revisit the strange `hybrid_fix_state` Jim added in the weirdest place.

Anyway I will drop the `else if`.

File: src/signals.c (hunk 3 above)
Comment (solardiz) [reply src/signals.c:408]: We should also care about async signal safety here. Luckily, that `tty_has_keyboard()` function you quoted looks safe. We could want to add a comment near the function itself that we depend on its async signal safety by using it in `sig_handle_timer()` in MPI builds.

File: src/signals.c [hunk 7]
```diff
@@ -323,9 +327,8 @@ static void sig_handle_timer(int signum)
 #endif
 #ifndef BENCH_BUILD
 #if OS_TIMER
-	/* Some stuff only done every few seconds */
-	if (timer_save_interval < 4 ||
-	    ((timer_save_interval - timer_save_value) & 3) == 3) {
+	/* Some stuff only done every fourth second */
+	if (((timer_save_interval - timer_save_value) & 3) == 0) {
```
Comment (solardiz) [inline src/signals.c:331]: Actually, checking for `== 1` (like you had before) might have been right, and `== 0` might be wrong now - perhaps `timer_save_interval` is at least 1, while `timer_save_value` can be 0, no? Have you tested this with either kind of check?

Comment (magnumripper) [reply src/signals.c:331]: `0` is correct and duly tested now. The `!OS_TIMER` side is less affected by other variables but I tested that as well.

File: doc/README.bash-completion [hunk 8]
```diff
@@ -159,9 +159,8 @@ $ john --fo=
 
 For a jumbo build, the first 4 examples will not work, because the option name
 is ambiguous.
-A jumbo version also has the options --field-separator-char= and
---fix-state-delay=, so at least the first two letters of the option name
-must be specified.
+A jumbo version also has the options --field-separator-char=, so at least the
+first two letters of the option name must be specified.
```
Comment (magnumripper) [inline doc/README.bash-completion]: I decided to revert the changes to this file, because it mentions a specific Jumbo version for the examples.

File: src/cracker.c [hunk 9]
```diff
@@ -208,10 +205,10 @@ void crk_init(struct db_main *db, void (*fix_state)(void),
...
 	crk_last_salt = NULL;
 
-	if (fix_state)
-		(crk_fix_state = fix_state)();
-	else
-		crk_fix_state = crk_dummy_fix_state;
+	fix_state_present = fix_state || (options.flags & FLG_MASK_STACKED);
+
+	if ((crk_fix_state = fix_state))
+		crk_fix_state();
```
Comment (magnumripper) [inline src/cracker.c]: I now reverted this and went back with the original `crk_dummy_fix_state()` instead of `fix_state_present`, because allowing `crk_fix_state` to be NULL would be error-prone in hybrid modes.
