### PR TITLE
zip2john: Default to using single byte checksums

### LINKED ISSUE #4541: zip2john doesn't produce a crackable hash when zip was created with bsdtar
Hi and thanks a lot for JtR!

I think that zip2john doesn't work when the zip file was created with bsdtar:

    bsdtar --options zip:encryption -acf with_bsdtar.zip test_file

Here's the example [`with_bsdtar.zip`](https://github.com/openwall/john/files/5777014/with_bsdtar.zip), the password is "test".

The output of `zip2john with_bsdtar.zip`:

    ver 2.0 efh 5455 efh 7875 with_bsdtar.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=0, decmplen=6, crc=0
    with_bsdtar.zip/test_file:$pkzip2$1*2*2*0*0*6*0*0*47*8*0*0000*8cd0**$/pkzip2$:test_file:with_bsdtar.zip::with_bsdtar.zip

On the other hand, things work fine when using a zip file created with

    zip --encrypt with_zip.zip test_file

where `zip2john with_zip.zip` yields

    ver 1.0 efh 5455 efh 7875 with_zip.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=18, decmplen=6, crc=775F54D8
    with_zip.zip/test_file:$pkzip2$1*2*2*0*12*6*775f54d8*0*43*0*12*775f*8cd0*a5ad914fcad388ac41ecf2a97498c2315730*$/pkzip2$:test_file:with_zip.zip::with_zip.zip

Here's [`with_zip.zip`](https://github.com/openwall/john/files/5777077/with_zip.zip).

The archive `with_bsdtar.zip` seems to be valid, since I can `unzip with_bsdtar.zip` successfully.

### System configuration ###
I'm on Arch Linux 5.9.14.

Output of `john --list=build-info`:

    Version: 1.9.0-jumbo-1
    Build: linux-gnu 64-bit x86_64 AVX AC MPI + OMP
    SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
    System-wide exec: /usr/lib/john
    System-wide home: /usr/share/john
    Private home: ~/.john
    CPU tests: AVX
    CPU fallback binary: john-non-avx
    $JOHN is /usr/share/john/
    Format interface version: 14
    Max. number of reported tunable costs: 4
    Rec file version: REC4
    Charset file version: CHR3
    CHARSET_MIN: 1 (0x01)
    CHARSET_MAX: 255 (0xff)
    CHARSET_LENGTH: 24
    SALT_HASH_SIZE: 1048576
    SINGLE_IDX_MAX: 2147483648
    SINGLE_BUF_MAX: 4294967295
    Effective limit: Number of salts vs. SingleMaxBufferSize
    Max. Markov mode level: 400
    Max. Markov mode password length: 30
    gcc version: 10.2.0
    GNU libc version: 2.32 (loaded: 2.32)
    OpenCL headers version: 2.2
    Crypto library: OpenSSL
    OpenSSL library version: 01010108f	(loaded: 01010109f)
    OpenSSL 1.1.1h  22 Sep 2020	(loaded: OpenSSL 1.1.1i  8 Dec 2020)
    GMP library version: 6.2.0	(loaded: 6.2.1)
    File locking: fcntl()
    fseek(): fseek
    ftell(): ftell
    fopen(): fopen
    memmem(): System's

### PR DESCRIPTION
**Pull request by magnumripper**
This may mean ~10% performance loss but the alternative seems to be risk of false negatives.
The existing -2 option was changed to "allow" instead of "force" 2-byte checksums.

Closes #4541, see also #4300.

### CODE REVIEW

File: src/zip2john.c [hunk 1]
```diff
@@ -779,7 +779,8 @@ static int process_legacy(zip_file *zfp, zip_ptr *p)
 				// OLD winzip (I think 8.01 or before), is also supposed to be 2 byte.
 				// old v1 pkzip (the DOS builds) are 2 byte checksums.
 			{
-				zfp->check_bytes = 2;
+				if (allow_2_byte_checksum) // See #4541
+					zfp->check_bytes = 2;
```
Comment (solardiz) [inline src/zip2john.c:783]: Isn't it weird/wrong that we only use 2-byte checksum conditionally even after having checked for very specific `efh_id` values? Don't those known values guarantee we have 2-byte? Confused.

Comment (solardiz) [reply src/zip2john.c:783]: > Don't those known values guarantee we have 2-byte

OK, I see that the issue we're trying to fix is `0x7875` doesn't guarantee 2-byte checksum.

I think we should add a comment that unfortunately checksum size seen with that EFH value varies between the two known archivers that use that value.

Comment (solardiz) [reply src/zip2john.c:783]: So the main question is whether we want to hurt the speed at all other previously-whitelisted EFH values just because we found this problem for `0x7875` now. I doubt we want to do that, or at least we should have `zip2john` recommend use of `-2` for those. In fact, it could print a more verbose recommendation even for `0x7875`, mentioning the `bsdtar` issue.

**Comment by ghost** [comment]
IMO, we should merge this as is to fix the known issue (false negative). Then discuss if there is a better approach.

**Comment by solardiz** [comment]
@claudioandre-br OK, I've just merged this, although I am unhappy we're hurting performance even at EFH values for which no known problems exist.
