### PR TITLE
odf formats: fix overflow in odf_prepare() replacing implementation

### LINKED ISSUE #4980: ODF format ASan crash seen in multi-format --fuzz
```
$ OMP_NUM_THREADS=1 time ../run/john -fuzz -format=-md5crypt-long,-scrypt,-andOTP,-argon2,-as400-ssha1,-agilekeychain,-axcrypt,-AndroidBackup,-BestCrypt,-bks,-diskcryptor,-dmg,-dmd5,-DPAPImk,-electrum,-Fortigate256,-Bitcoin,-BitLocker,-bitshares,-ethereum,-Fortigate,-hdaa,-keepass,-krb5tgs,-leet,-luks,-monero,-mscash,-mscash2,-pgpwde,-radius,-sappse,-telegram
[...]
Fuzzing: ODF, OpenDocument Star/Libre/OpenOffice [PBKDF2-SHA1 128/128 AVX 4x BF/AES]... ASAN:SIGSEGV
=================================================================
==16307==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f8d578719df sp 0x7fff5af5b6d8 bp 0x7fff5af5bf40 T0)
    #0 0x7f8d578719de in __strlen_sse42 (/lib64/libc.so.6+0x1339de)
    #1 0x7f8d596d3f46 in __interceptor_strcpy (/usr/lib64/libasan.so.1+0x2ef46)
    #2 0x776d1e in odf_prepare /home/solar/j/syl/john/src/odf_common_plug.c:235
    #3 0x8b8d47 in ldr_split_line /home/solar/j/syl/john/src/loader.c:662
    #4 0x8baf92 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:958
    #5 0xbbac62 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:586
    #6 0xbbb04f in fuzz /home/solar/j/syl/john/src/fuzz.c:689
    #7 0x8ae597 in john_run /home/solar/j/syl/john/src/john.c:1672
    #8 0x8ae597 in main /home/solar/j/syl/john/src/john.c:2082
    #9 0x7f8d5775cd1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #10 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 __strlen_sse42
==16307==ABORTING
12156.22user 353.46system 3:28:42elapsed 99%CPU (0avgtext+0avgdata 27263748maxresident)k
408inputs+2694408outputs (2major+4908079minor)pagefaults 0swaps
```

### PR DESCRIPTION
**Pull request by AlekseyCherepanov**
(closes #4980)

### CODE REVIEW

File: src/odf_common_plug.c [hunk 1]
```diff
@@ -214,25 +214,38 @@ void *odf_get_binary(char *ciphertext)
...
-		strcpy(cp1, cp3);
+		len1 = cp - part1;
+		cp = strchr(cp, '*');
+		if (!cp)
+			return fields[1];
+		++cp;
+		part2 = cp;
+		len2 = strlen(part2);
+		if (FORMAT_TAG_LEN + len1 + len2 >= max_len - 1)
+			return fields[1];
```
Comment (solardiz) [inline src/odf_common_plug.c:240]: Doesn't this ensure room for 1 byte more than needed? I think it should be either `>=` or `- 1`, not both.

**Comment by AlekseyCherepanov** [comment]
Original implementation did not have any checks: `strchr` could return 0 and cause crash in further calls, both `strcpy` and `strncpy` could overflow buffer.

I found 5 different crashes: use of pointer 0x1 on lines 228, 231, 235, overflows on lines 231, 235.
```
python -c 'print "$sxc$*1*2*3*4*5*6*7*8*9"' > t.pw
python -c 'print "$sxc$*1*2*3*4*5*6*7*8*9*10"' > t.pw
python -c 'print "$sxc$*1*2*3*4*5*6*7*8*9*10*11"' > t.pw
python -c 'print "$sxc$*1*2*3*4*5*6*7*8*9*" + "a" * 4000 + "*11*12"' > t.pw
python -c 'print "$sxc$*1*2*3*4*5*6*7*8*9*10*11*" + "a" * 40000' > t.pw
```

I could not reproduce `SEGV on unknown address 0x000000000000` seen in #4980. I get 0x0...01 as in `cp = strchr(...); cp++; ...use...`.

I rewrote it to my taste: find parts and lengths, check sizes, then copy everything with `memcpy`.

`--test` is ok.

**Review by solardiz — APPROVED** [review]
I didn't fully review, but the overflow check looks OK (even too strict by 1 byte).

Since this touches a common file, perhaps manual testing of the OpenCL format is needed.

File: src/odf_common_plug.c (hunk 1 above)
Comment (AlekseyCherepanov) [reply src/odf_common_plug.c:240]: 1 additional byte is needed for null byte.

I thought to write it as `FORMAT_TAG_LEN + len1 + len2 + 1 >= max_len`. Would it be better?

OTOH I had thoughts to write `len1 + len2 >= max_len - 1 - FORMAT_TAG_LEN`, so constants would be reduced into one. And `len1 + len2` would not overflow `size_t` even if new tag would be longer one to be replaced (currently they have same length).

Comment (AlekseyCherepanov) [reply src/odf_common_plug.c:240]: Hm, I could include `+1` into `len2`. Then null byte would be copied by `memcpy`. It would save 2 lines of code.

Somehow I thought it would be more natural with bot parts lacking null byte. Now it does not seem so natural.

**Comment by AlekseyCherepanov** [comment]
I replaced commit to include `+1` into `len2`. `--test` for `odf` is ok. Slightly later I'll test `odf-opencl`.

File: src/odf_common_plug.c (hunk 1 above)
Comment (AlekseyCherepanov) [reply src/odf_common_plug.c:240]: I included `+1` into `len2` and replaced commit.

**Comment by AlekseyCherepanov** [comment]
```c
		cp = buf;
		memcpy(cp, FORMAT_TAG, FORMAT_TAG_LEN);
		cp += FORMAT_TAG_LEN;
		memcpy(cp, part1, len1);
		cp += len1;
		memcpy(cp, part2, len2);
```
It could be written this way:
```c
		memcpy(cp = buf,             FORMAT_TAG, FORMAT_TAG_LEN);
		memcpy(cp += FORMAT_TAG_LEN, part1,      len1);
		memcpy(cp += len1,           part2,      len2);
```
And it looks very tempting...

File: src/odf_common_plug.c (hunk 1 above)
Comment (solardiz) [reply src/odf_common_plug.c:240]: > 1 additional byte is needed for null byte.

Sure, but you left 2 bytes, not 1. I haven't reviewed your further changes here yet - I think they were unneeded.

**Comment by solardiz** [comment]
> And it looks very tempting...

No, please don't.

File: src/odf_common_plug.c (hunk 1 above)
Comment (solardiz) [reply src/odf_common_plug.c:240]: OK, the new changes look good to me, but you're still leaving 1 more byte unused. You can change the check from `>=` to `>`.

**Comment by AlekseyCherepanov** [comment]
`--test --format=odf-opencl` is ok in ASan build with amdgpu-pro.

Except a leak that does not seem related to `odf-opencl`:
```
=================================================================
==124672==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6000 byte(s) in 4 object(s) allocated from:
    #0 0x7f6c845b0e8f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f6c7c1d725f  (/opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so+0xf0125f)

SUMMARY: AddressSanitizer: 6000 byte(s) leaked in 4 allocation(s).
```

File: src/odf_common_plug.c (hunk 1 above)
Comment (AlekseyCherepanov) [reply src/odf_common_plug.c:240]: Indeed. Somehow I could compute it in my head and had to draw a scheme...

Comment (AlekseyCherepanov) [reply src/odf_common_plug.c:240]: s/could/could not/

**Comment by AlekseyCherepanov** [comment]
I replaced commit changing `>=` to `>`. Retested.
